Repository pooranjoyb/StoryBook-RN, pull requests merged in 2024-01, with the labels that each got.

#4 FIx : Persistent State of User Authentication #3
  App.tsx
  package-lock.json
  package.json
  utils/redux/store.ts
Labels: enhancement, JWOC, hard

#6 UI for the Profile (Upgraded Home, Login and Register screen UI)
  App.tsx
  Components/Home.tsx
  Components/Login.tsx
  Components/Profile.tsx
  Components/Signup.tsx
  app.json
  package-lock.json
  package.json
Labels: medium, JWOC

#11 Design the Home Screen 🚀 (Updated Profile Screen)
  App.tsx
  Components/Profile.tsx
  Components/StoriesList.tsx
  package-lock.json
  package.json
Labels: medium, JWOC

#9 Redesign the UI for Stories List
  Components/StoriesList.tsx
Labels: medium, JWOC

#14 Redesign the UI for Stories List 🚀 (Redesigned, added more functionalities and fix some errors)
  App.tsx
  Components/Footer.tsx
  Components/Login.tsx
  Components/Profile.tsx
  Components/StoriesList.tsx
  package-lock.json
  package.json
Labels: JWOC, hard

#18 UI for the Stories Page 🚀
  App.tsx
  Components/Profile.tsx
  Components/Stories.tsx
  Components/StoriesList.tsx
Labels: medium, JWOC
